#nullable enable

namespace DeskPulse;

partial class ViewLogForm
{
    private System.ComponentModel.IContainer? components = null;
    private System.Windows.Forms.DateTimePicker dateStart = null!;
    private System.Windows.Forms.DateTimePicker dateEnd = null!;
    private System.Windows.Forms.ComboBox periodCombo = null!;
    private System.Windows.Forms.Button refreshButton = null!;
    private System.Windows.Forms.Button exportButton = null!;
    private System.Windows.Forms.Button calendarViewButton = null!;
    private System.Windows.Forms.Button createRuleButton = null!;
    private System.Windows.Forms.Button deleteButton = null!;
    private System.Windows.Forms.Label statusLabel = null!;
    private System.Windows.Forms.Panel pagingPanel = null!;
    private System.Windows.Forms.Button firstPageButton = null!;
    private System.Windows.Forms.Button previousPageButton = null!;
    private System.Windows.Forms.Button nextPageButton = null!;
    private System.Windows.Forms.Button lastPageButton = null!;
    private System.Windows.Forms.Label pageLabel = null!;
    private System.Windows.Forms.Label pageSizeLabel = null!;
    private System.Windows.Forms.NumericUpDown pageSizeInput = null!;
    private System.Windows.Forms.Button applyPageSizeButton = null!;
    private System.Windows.Forms.Label groupByLabel = null!;
    private System.Windows.Forms.ComboBox groupByCombo = null!;
    private System.Windows.Forms.Panel calendarHostPanel = null!;
    private System.Windows.Forms.TabControl tabs = null!;
    private System.Windows.Forms.DataGridView gridApp = null!;
    private System.Windows.Forms.DataGridView gridFile = null!;
    private System.Windows.Forms.DataGridView gridUser = null!;

    protected override void Dispose(bool disposing)
    {
        if (disposing) components?.Dispose();
        base.Dispose(disposing);
    }

    private void InitializeComponent()
    {
        components = new System.ComponentModel.Container();
        var topPanel = new System.Windows.Forms.Panel();
        var startLabel = new System.Windows.Forms.Label();
        var endLabel = new System.Windows.Forms.Label();
        var appTab = new System.Windows.Forms.TabPage();
        var fileTab = new System.Windows.Forms.TabPage();
        var userTab = new System.Windows.Forms.TabPage();
        dateStart = new System.Windows.Forms.DateTimePicker();
        dateEnd = new System.Windows.Forms.DateTimePicker();
        periodCombo = new System.Windows.Forms.ComboBox();
        refreshButton = new System.Windows.Forms.Button();
        exportButton = new System.Windows.Forms.Button();
        calendarViewButton = new System.Windows.Forms.Button();
        createRuleButton = new System.Windows.Forms.Button();
        deleteButton = new System.Windows.Forms.Button();
        statusLabel = new System.Windows.Forms.Label();
        pagingPanel = new System.Windows.Forms.Panel();
        firstPageButton = new System.Windows.Forms.Button();
        previousPageButton = new System.Windows.Forms.Button();
        nextPageButton = new System.Windows.Forms.Button();
        lastPageButton = new System.Windows.Forms.Button();
        pageLabel = new System.Windows.Forms.Label();
        pageSizeLabel = new System.Windows.Forms.Label();
        pageSizeInput = new System.Windows.Forms.NumericUpDown();
        applyPageSizeButton = new System.Windows.Forms.Button();
        groupByLabel = new System.Windows.Forms.Label();
        groupByCombo = new System.Windows.Forms.ComboBox();
        calendarHostPanel = new System.Windows.Forms.Panel();
        tabs = new System.Windows.Forms.TabControl();
        gridApp = new System.Windows.Forms.DataGridView();
        gridFile = new System.Windows.Forms.DataGridView();
        gridUser = new System.Windows.Forms.DataGridView();
        topPanel.SuspendLayout();
        tabs.SuspendLayout();
        pagingPanel.SuspendLayout();
        appTab.SuspendLayout();
        fileTab.SuspendLayout();
        userTab.SuspendLayout();
        ((System.ComponentModel.ISupportInitialize)gridApp).BeginInit();
        ((System.ComponentModel.ISupportInitialize)gridFile).BeginInit();
        ((System.ComponentModel.ISupportInitialize)gridUser).BeginInit();
        ((System.ComponentModel.ISupportInitialize)pageSizeInput).BeginInit();
        SuspendLayout();
        topPanel.Controls.Add(calendarViewButton);
        topPanel.Controls.Add(startLabel);
        topPanel.Controls.Add(dateStart);
        topPanel.Controls.Add(endLabel);
        topPanel.Controls.Add(dateEnd);
        topPanel.Controls.Add(periodCombo);
        topPanel.Controls.Add(refreshButton);
        topPanel.Controls.Add(exportButton);
        topPanel.Controls.Add(createRuleButton);
        topPanel.Controls.Add(deleteButton);
        topPanel.Controls.Add(groupByLabel);
        topPanel.Controls.Add(groupByCombo);
        topPanel.Dock = System.Windows.Forms.DockStyle.Top;
        topPanel.Height = 52;
        topPanel.Resize += (_, _) =>
        {
            var compact = topPanel.ClientSize.Width < 1180;
            topPanel.Height = compact ? 88 : 52;
            createRuleButton.Location = compact
                ? new System.Drawing.Point(12, 52)
                : new System.Drawing.Point(922, 12);
            deleteButton.Location = compact
                ? new System.Drawing.Point(116, 52)
                : new System.Drawing.Point(1026, 12);
            groupByLabel.Location = compact
                ? new System.Drawing.Point(214, 58)
                : new System.Drawing.Point(1110, 18);
            groupByLabel.Size = compact
                ? new System.Drawing.Size(300, 20)
                : new System.Drawing.Size(100, 20);
        };
        calendarViewButton.Location = new System.Drawing.Point(12, 12);
        calendarViewButton.Size = new System.Drawing.Size(105, 29);
        calendarViewButton.Text = "Calendar View";
        calendarViewButton.UseVisualStyleBackColor = true;
        calendarViewButton.Click += CalendarViewButton_Click;
        startLabel.AutoSize = true;
        startLabel.Location = new System.Drawing.Point(214, 18);
        startLabel.Text = "From:";
        dateStart.Format = System.Windows.Forms.DateTimePickerFormat.Custom;
        dateStart.CustomFormat = "dd/MM/yyyy HH:mm";
        dateStart.Location = new System.Drawing.Point(260, 14);
        dateStart.Width = 135;
        endLabel.AutoSize = true;
        endLabel.Location = new System.Drawing.Point(407, 18);
        endLabel.Text = "To:";
        dateEnd.Format = System.Windows.Forms.DateTimePickerFormat.Custom;
        dateEnd.CustomFormat = "dd/MM/yyyy HH:mm";
        dateEnd.Location = new System.Drawing.Point(437, 14);
        dateEnd.Width = 135;
        periodCombo.DropDownStyle = System.Windows.Forms.ComboBoxStyle.DropDownList;
        periodCombo.Location = new System.Drawing.Point(584, 14);
        periodCombo.Size = new System.Drawing.Size(150, 23);
        periodCombo.SelectedIndexChanged += PeriodCombo_SelectedIndexChanged;
        refreshButton.Location = new System.Drawing.Point(744, 12);
        refreshButton.Size = new System.Drawing.Size(78, 29);
        refreshButton.Text = "Refresh";
        refreshButton.UseVisualStyleBackColor = true;
        refreshButton.Click += RefreshButton_Click;
        createRuleButton.Enabled = false;
        createRuleButton.Location = new System.Drawing.Point(922, 12);
        createRuleButton.Size = new System.Drawing.Size(96, 29);
        createRuleButton.Text = "Create Rule";
        createRuleButton.UseVisualStyleBackColor = true;
        createRuleButton.Click += CreateRuleButton_Click;
        deleteButton.Enabled = false;
        deleteButton.Location = new System.Drawing.Point(1026, 12);
        deleteButton.Size = new System.Drawing.Size(76, 29);
        deleteButton.Text = "Delete";
        deleteButton.UseVisualStyleBackColor = true;
        deleteButton.Click += DeleteButton_Click;
        groupByLabel.AutoSize = false;
        groupByLabel.Location = new System.Drawing.Point(1110, 18);
        groupByLabel.Size = new System.Drawing.Size(100, 20);
        groupByLabel.Text = "Double-click a heading to group";
        groupByCombo.DropDownStyle = System.Windows.Forms.ComboBoxStyle.DropDownList;
        groupByCombo.Location = new System.Drawing.Point(940, 14);
        groupByCombo.Size = new System.Drawing.Size(130, 23);
        groupByCombo.Items.AddRange(new object[] { "None", "Date", "File name", "Extension", "Folder", "Application", "Activity" });
        groupByCombo.SelectedIndex = 0;
        groupByCombo.SelectedIndexChanged += GroupByCombo_SelectedIndexChanged;
        groupByCombo.Visible = false;
        exportButton.Location = new System.Drawing.Point(830, 12);
        exportButton.Size = new System.Drawing.Size(84, 29);
        exportButton.Text = "Export";
        exportButton.UseVisualStyleBackColor = true;
        exportButton.Click += ExportButton_Click;
        tabs.Controls.Add(fileTab);
        tabs.Controls.Add(appTab);
        tabs.Controls.Add(userTab);
        tabs.Dock = System.Windows.Forms.DockStyle.Fill;
        appTab.Controls.Add(gridApp);
        appTab.Text = "App Activity";
        fileTab.Controls.Add(gridFile);
        fileTab.Text = "File Activity";
        userTab.Controls.Add(gridUser);
        userTab.Text = "User Activity";
        gridApp.Dock = System.Windows.Forms.DockStyle.Fill;
        gridFile.Dock = System.Windows.Forms.DockStyle.Fill;
        gridUser.Dock = System.Windows.Forms.DockStyle.Fill;
        pagingPanel.Controls.Add(pageSizeLabel);
        pagingPanel.Controls.Add(pageSizeInput);
        pagingPanel.Controls.Add(applyPageSizeButton);
        pagingPanel.Controls.Add(firstPageButton);
        pagingPanel.Controls.Add(previousPageButton);
        pagingPanel.Controls.Add(nextPageButton);
        pagingPanel.Controls.Add(lastPageButton);
        pagingPanel.Controls.Add(pageLabel);
        pagingPanel.Dock = System.Windows.Forms.DockStyle.Bottom;
        pagingPanel.Height = 42;
        pageSizeLabel.Location = new System.Drawing.Point(12, 13);
        pageSizeLabel.Text = "Records per page:";
        pageSizeInput.Location = new System.Drawing.Point(122, 9);
        pageSizeInput.Minimum = 1;
        pageSizeInput.Maximum = 10000;
        pageSizeInput.Value = 500;
        pageSizeInput.Size = new System.Drawing.Size(75, 23);
        applyPageSizeButton.Location = new System.Drawing.Point(203, 7);
        applyPageSizeButton.Size = new System.Drawing.Size(58, 28);
        applyPageSizeButton.Text = "Apply";
        applyPageSizeButton.UseVisualStyleBackColor = true;
        applyPageSizeButton.Click += ApplyPageSizeButton_Click;
        firstPageButton.Location = new System.Drawing.Point(275, 7);
        firstPageButton.Size = new System.Drawing.Size(105, 28);
        firstPageButton.Text = "<< First Page";
        firstPageButton.UseVisualStyleBackColor = true;
        firstPageButton.Click += FirstPageButton_Click;
        previousPageButton.Location = new System.Drawing.Point(386, 7);
        previousPageButton.Size = new System.Drawing.Size(120, 28);
        previousPageButton.Text = "< Previous Page";
        previousPageButton.UseVisualStyleBackColor = true;
        previousPageButton.Click += PreviousPageButton_Click;
        nextPageButton.Location = new System.Drawing.Point(512, 7);
        nextPageButton.Size = new System.Drawing.Size(110, 28);
        nextPageButton.Text = "Next Page >";
        nextPageButton.UseVisualStyleBackColor = true;
        nextPageButton.Click += NextPageButton_Click;
        lastPageButton.Location = new System.Drawing.Point(628, 7);
        lastPageButton.Size = new System.Drawing.Size(105, 28);
        lastPageButton.Text = "Last Page >>";
        lastPageButton.UseVisualStyleBackColor = true;
        lastPageButton.Click += LastPageButton_Click;
        pageLabel.Anchor = System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Right;
        pageLabel.Location = new System.Drawing.Point(951, 12);
        pageLabel.Size = new System.Drawing.Size(263, 20);
        pageLabel.Text = "Page 1 of 1";
        pageLabel.TextAlign = System.Drawing.ContentAlignment.MiddleRight;
        statusLabel.Dock = System.Windows.Forms.DockStyle.Bottom;
        statusLabel.Height = 30;
        statusLabel.Padding = new System.Windows.Forms.Padding(10, 7, 0, 0);
        statusLabel.Text = "Ready.";
        calendarHostPanel.Dock = System.Windows.Forms.DockStyle.Fill;
        calendarHostPanel.Visible = false;
        AutoScaleDimensions = new System.Drawing.SizeF(7F, 15F);
        AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
        ClientSize = new System.Drawing.Size(1220, 680);
        Controls.Add(tabs);
        Controls.Add(calendarHostPanel);
        Controls.Add(pagingPanel);
        Controls.Add(statusLabel);
        Controls.Add(topPanel);
        MinimumSize = new System.Drawing.Size(1000, 500);
        StartPosition = System.Windows.Forms.FormStartPosition.CenterScreen;
        Text = "DeskPulse - Log (Current User)";
        WindowState = System.Windows.Forms.FormWindowState.Maximized;
        topPanel.ResumeLayout(false);
        topPanel.PerformLayout();
        tabs.ResumeLayout(false);
        pagingPanel.ResumeLayout(false);
        appTab.ResumeLayout(false);
        fileTab.ResumeLayout(false);
        userTab.ResumeLayout(false);
        ((System.ComponentModel.ISupportInitialize)gridApp).EndInit();
        ((System.ComponentModel.ISupportInitialize)gridFile).EndInit();
        ((System.ComponentModel.ISupportInitialize)gridUser).EndInit();
        ((System.ComponentModel.ISupportInitialize)pageSizeInput).EndInit();
        ResumeLayout(false);
    }
}
